"""Initial commit

Revision ID: 001443de26cf
Revises: 
Create Date: 2026-04-11 13:07:26.804757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001443de26cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('water_liters', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_records_date'), 'irrigation_records', ['date'], unique=False)
    op.create_index(op.f('ix_irrigation_records_id'), 'irrigation_records', ['id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('nse', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_model_metrics_module'), 'model_metrics', ['module'], unique=False)
    op.create_table('nasa_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nasa_data_date'), 'nasa_data', ['date'], unique=True)
    op.create_index(op.f('ix_nasa_data_id'), 'nasa_data', ['id'], unique=False)
    op.create_table('rainfall_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('actual_mm', sa.Float(), nullable=True),
    sa.Column('predicted_mm', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainfall_records_date'), 'rainfall_records', ['date'], unique=True)
    op.create_index(op.f('ix_rainfall_records_id'), 'rainfall_records', ['id'], unique=False)
    op.create_table('tank_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('level_status', sa.String(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('roof_area', sa.Float(), nullable=True),
    sa.Column('tank_capacity', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tank_records_date'), 'tank_records', ['date'], unique=False)
    op.create_index(op.f('ix_tank_records_id'), 'tank_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tank_records_id'), table_name='tank_records')
    op.drop_index(op.f('ix_tank_records_date'), table_name='tank_records')
    op.drop_table('tank_records')
    op.drop_index(op.f('ix_rainfall_records_id'), table_name='rainfall_records')
    op.drop_index(op.f('ix_rainfall_records_date'), table_name='rainfall_records')
    op.drop_table('rainfall_records')
    op.drop_index(op.f('ix_nasa_data_id'), table_name='nasa_data')
    op.drop_index(op.f('ix_nasa_data_date'), table_name='nasa_data')
    op.drop_table('nasa_data')
    op.drop_index(op.f('ix_model_metrics_module'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_irrigation_records_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_date'), table_name='irrigation_records')
    op.drop_table('irrigation_records')
    # ### end Alembic commands ###
