"""add pressure to nasa_data

Revision ID: 41b433963f02
Revises: 001443de26cf
Create Date: 2026-04-29 07:47:34.761925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b433963f02'
down_revision: Union[str, Sequence[str], None] = '001443de26cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nasa_data', sa.Column('pressure', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nasa_data', 'pressure')
    # ### end Alembic commands ###
